..  |ACC|           replace:: Austin Community College
..  _ACC:           http://www.austincc.edu/
..  |WWW|           replace:: World-Wide-Web
..  |RST|           replace:: reStructuredText
..  |PY|            replace:: *Python*

..  _`Donald Knuth`:    http://www-cs-faculty.stanford.edu/~knuth/
..  _`Leslie Lamport`:  http://www.lamport.org/

..  _Adafruit:      http://www.adafruit.com/
..  _Amazon:        https://aws.amazon.com/
..  _Ansible:       http://www.ansible.com/home
..  _BibTeX:        http://www.bibtex.org/
..  _DropBox:       https://www.dropbox.com
..  _Git:           http://git-scm.com/
..  _GitLab:        https://about.gitlab.com/
..  _GitHub:        https://github.com/
..  _GitWeb:        http://git-scm.com/docs/gitweb.html
..  _GitPython:     https://pypi.python.org/pypi/GitPython/
..  _gMail:         http://www.gmail.com/
..  _Gnu:           https://www.gnu.org/
..  _gVim:          http://www.vim.org/
..  _Homebrew:      http://brew.sh/
..  _MacTeX:        https://tug.org/mactex/
..  _Make:          https://www.gnu.org/software/make/
..  _Pip:           https://pip.pypa.io/en/stable/
..  _Python:        https://www.python.org/
..  _RaspberryPI:   http://www.raspberrypi.org/
..  _Sphinx:        http://sphinx-doc.org/
..  _Vim:           http://www.vim.org/

